// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fjnwpufgugclqacphnii.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZqbndwdWZndWdjbHFhY3BobmlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg2MTc2OTMsImV4cCI6MjA1NDE5MzY5M30.oLDChYZq5Vl-zNsLEvXYGkpigSAbMRjqH-VcQutIUbM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);